# CI de nível 01 - Disparo manual através de click

# nome da pipeline
name: 'Execução Manual'

# gatilhos ou triggers

# gatilho manual
on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    
    # passos do job
    steps:
      # clone do projeto
      - uses: action/checkout@v4
      
      # instalação do node
      - uses: action/setup-node@v4
        with:
          node-version: 24.x

      # instalação do yarn
      - name: Instalando yarn
        run: npm install -g yarn

      # instalação das dependências
      - name: Instalando dependências
        run: yarn

      # instalação dos Browsers do playwright
      - name: Instalando Browsers do playwright
        run: yarn playwright install

      # execução dos testes e2e
      - name: Executando testes e2e
        run: yarn run e2e